project_id = "hschwipsafvnlyujmkfq"

[functions.create-test-users]
verify_jwt = false

[functions.seed-teachers]
verify_jwt = false

[functions.add-teacher]
verify_jwt = false

[functions.update-teacher]
verify_jwt = false

[functions.remove-teacher]
verify_jwt = false

[functions.reset-teacher-password]
verify_jwt = false
